# Use ONE of the two options below.

# Option A: single URL (recommended)
# Replace with your actual URL from Render -> Connect -> External URL
DB_URL = "postgresql+psycopg2://USER:ENCODED_PASSWORD@dpg-abc123-xyz.region-postgres.render.com:5432/DBNAME?sslmode=require"

# Option B: fields (the app will construct the URL and encode the password for you)
[postgres]
host     = "dpg-abc123-xyz.region-postgres.render.com"
port     = 5432
database = "auto_intel"
user     = "auto_intel_ro"
password = "CHANGE_ME"
